{
 "title": "Anomaly Operations Overview",
 "description": "Goal: quick operational view of anomalies and model health.",
 "tags": [
  "anomaly",
  "overview"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Anomalies in P1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ae_anomalies_in_batch{stage=\"P1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anomalies in P2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ae_anomalies_in_batch{stage=\"P2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anomalies in P3",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ae_anomalies_in_batch{stage=\"P3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anomalies in P4",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ae_anomalies_in_batch{stage=\"P4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anomalies in P5",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ae_anomalies_in_batch{stage=\"P5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anomalies in P6",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ae_anomalies_in_batch{stage=\"P6\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anomalies on P1 over time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ae_anomalies_total{stage=\"P1\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Anomalies on P2 over time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ae_anomalies_total{stage=\"P2\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Anomalies on P3 over time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ae_anomalies_total{stage=\"P3\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Anomalies on P4 over time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ae_anomalies_total{stage=\"P4\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Anomalies on P5 over time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ae_anomalies_total{stage=\"P5\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Anomalies on P6 over time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ae_anomalies_total{stage=\"P6\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Reconstruction Error Distribution by Sensor",
   "type": "heatmap",
   "description": "Displays the frequency distribution of the Autoencoder's reconstruction error across all monitored sensors over time.",
   "gridPos": { "h": 31, "w": 7, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(ae_reconstruction_error_bucket[5m])) by (le,sensor)",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Batches processed total",
   "type": "stat",
   "description": "If batches_processed_total continues to increase, Spark is processing streaming batches normally.",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ae_batches_processed_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Batch processing in the last 5 minutes",
   "type": "stat",
   "description": "The stat graph shows the rate of batch processing in the last 5 minutes.\nIf the sparkline suddenly drops → Spark lag, overloaded pipeline, Kafka delay, or model freeze.",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ae_batches_processed_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top-N bar for anomalies",
   "type": "barchart",
   "description": "Identify the sensors that have had the biggest increase in flagged anomalies in the last 10 minutes.",
   "gridPos": { "h": 15, "w": 17, "x": 7, "y": 41 },
   "targets": [
    {
     "expr": "topk(10, increase(ae_anomalies_total[10m]))",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}