{
 "title": "Pattern mining",
 "tags": [ "pattern" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Count of events per window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"swat_db\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"pattern_events\" and r._field == \"severity\")\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)\r\n\r\n"
    }
   ]
  },
  {
   "title": "Last severity per window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"swat_db\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"pattern_events\" and\r\n      r._field == \"severity\" and\r\n      r.pattern == \"FIT_drop_then_LIT_rise\" and\r\n      r.sensor == \"FIT101->LIT101\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Event table",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket:\"swat_db\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"pattern_events\")\r\n  |> filter(fn: (r) => r[\"pattern\"] == \"FIT_drop_then_LIT_rise\")\r\n  |> filter(fn: (r) => r[\"sensor\"] == \"FIT101->LIT101\")\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\",\"pattern\",\"sensor\"])\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 100)"
    }
   ]
  }
 ]
}