apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: ics
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command: ["sh", "-c", "until nc -zv kafka 9092; do echo 'waiting for kafka'; sleep 1; done"]
      containers:
        - name: producer
          image: henrikberenyi/producer:latest
          imagePullPolicy: Always
      restartPolicy: Always
