apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ics
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # placeholder: scrape application metrics endpoints (add your services here)
      - job_name: 'app_metrics'
        static_configs:
          - targets: ['kafka:9092']   # replace with real /metrics endpoints later
